---
driver:
  name: vagrant
  network:
  - ["forwarded_port", { guest: 9000, host: 9000 }]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[kafka-manager::default]
    attributes:
      java:
        jdk_version: 7
      kafka-manager:
        zkhosts: "foo:1234,bar:5678"
